# Generated by Django 4.0.4 on 2022-05-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plerk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='date_transaction',
            new_name='date',
        ),
    ]
