# Generated by Django 4.0.4 on 2022-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plerk', '0002_rename_date_transaction_transaccion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='final_charge',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
