# Generated by Django 4.0.4 on 2022-05-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plerk', '0003_remove_transaccion_final_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
