# Generated by Django 4.0.4 on 2022-05-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plerk', '0007_alter_transaccion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='status_transaction',
            field=models.CharField(choices=[('closed', 'closed'), ('reversed', 'reversed'), ('pending', 'pending')], max_length=20),
        ),
    ]
